[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "alt-web01"
version = "0.1.0"
description = "A demonstration framework for simulating university enrollment and graduation."
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [{ name = "alt_web01 contributors" }]
classifiers = [
    "Framework :: Flask",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "Flask>=3.1,<4",
    "gunicorn>=23,<24",
    "class-roster-simulator @ git+https://github.com/gujiahui234/class_roster_simulator-0.1.0.git@ver0.2.0",
    "sclog_lite @ git+https://github.com/gujiahui234/sclog_lite.git@ver0.3.0"
]

[tool.hatch.metadata]
allow-direct-references = true

[project.urls]
Repository = "https://github.com/gujiahui234/website1"

[tool.hatch.build.targets.wheel]
packages = ["src/alt_web01"]
